@startuml
set separator none
title Identity

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Component>

Container_Boundary("HospitalErpApplication.HospitalErpApplication_boundary", "HospitalErpApplication", $tags="") {
  Component(HospitalErpApplication.HospitalErpApplication.Common, "Common", $techn="Module", $descr="", $tags="", $link="")
  Component(HospitalErpApplication.HospitalErpApplication.Notifications, "Notifications", $techn="Module", $descr="", $tags="", $link="")
  Component(HospitalErpApplication.HospitalErpApplication.Identity, "Identity", $techn="Module", $descr="", $tags="", $link="")
}

Rel(HospitalErpApplication.HospitalErpApplication.Identity, HospitalErpApplication.HospitalErpApplication.Common, "depends on", $techn="", $tags="", $link="")
Rel(HospitalErpApplication.HospitalErpApplication.Identity, HospitalErpApplication.HospitalErpApplication.Notifications, "uses", $techn="", $tags="", $link="")

SHOW_LEGEND(true)
@enduml